name: Upload To Azure
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: "/"
          AZURE_CLIENT_ID: "d87414e5-c12b-4b4c-98d8-cf4ac2baefb3"
          AZURE_TENANT_ID: "64d88933-7ef7-42d1-993d-11c436f2483f"
          AZURE_SECRET: "AKAlf7H1FqqOGtjCT4zO377WHp~umdvmkl"
          AZURE_SUBSCRIPTION_ID: "a16de862-e4f1-45f1-9862-cd8547d9d3ed"
          AZURE_STORAGE_ACCOUNT_NAME: "teststatic11"
          AZURE_INDEX_DOCUMENT_NAME: "index.html"
          AZURE_ERROR_DOCUMENT_NAME: "404.html"
