name: Blob storage website CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
env:

  AZURE_RESOURCE_GROUP: Testing
  BLOB_STORAGE_ACCOUNT_NAME: teststatic11
  CDN_NAME: https://teststatic11.azureedge.net

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.BLOB_STORAGE_ACCOUNT_NAME }} -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name ${{ env.BLOB_STORAGE_ACCOUNT_NAME }} --name ${{ env.CDN_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

  # Azure logout 
    - name: logout
      run: |
            az logout
